# Generated by Django 2.0.7 on 2019-04-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='feedback',
        ),
        migrations.AddField(
            model_name='chat',
            name='message',
            field=models.TextField(default='please enter the text'),
        ),
        migrations.AddField(
            model_name='chat',
            name='username',
            field=models.CharField(default='username', max_length=50),
        ),
    ]
