# Generated by Django 2.0.7 on 2019-04-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='username1',
            field=models.CharField(default='enter the valid username', max_length=50),
        ),
    ]
